title: "Javier Galeano Prieto"
description: "Catedrático de Universidad · UPM · Física Estadística, Sistemas Complejos, Redes, Biofísica"
url: ""
baseurl: ""
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
